[package]
name = "lucide-dioxus"
description = "Dioxus port of Lucide."
homepage = "https://lucide.rustforweb.org/frameworks/dioxus.html"

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
dioxus.workspace = true

[features]
default = []
accessibility = []
account = []
animals = []
arrows = []
brands = []
buildings = []
charts = []
communication = []
connectivity = []
cursors = []
design = []
development = []
devices = []
emoji = []
files = []
finance = []
food-beverage = []
gaming = []
home = []
layout = []
mail = []
math = []
medical = []
multimedia = []
nature = []
navigation = []
notifications = []
people = []
photography = []
science = []
seasons = []
security = []
shapes = []
shopping = []
social = []
sports = []
sustainability = []
text = []
time = []
tools = []
transportation = []
travel = []
weather = []
all-icons = [
    "accessibility",
    "account",
    "animals",
    "arrows",
    "brands",
    "buildings",
    "charts",
    "communication",
    "connectivity",
    "cursors",
    "design",
    "development",
    "devices",
    "emoji",
    "files",
    "finance",
    "food-beverage",
    "gaming",
    "home",
    "layout",
    "mail",
    "math",
    "medical",
    "multimedia",
    "nature",
    "navigation",
    "notifications",
    "people",
    "photography",
    "science",
    "seasons",
    "security",
    "shapes",
    "shopping",
    "social",
    "sports",
    "sustainability",
    "text",
    "time",
    "tools",
    "transportation",
    "travel",
    "weather",
]
